{
    "maintenance": False,
    "pdxl": False,
    "disable_illustrious": False,
    "pdxl_max_steps": 45,
    "max_loras": 5,
    "max_loras_pdxl": 5,
    "max_loras_flux": 3,
    "max_loras_illustrious": 3,
    "illustrious_max_steps": 45,
    "sd3_resolution_multiplier": 1,
    "pdxl_resolution_multiplier": 1,
    "illustrious_resolution_multiplier": 1,
    "sd15_resolution_multiplier": 1,
    "upscale": True,
    "sd3_users": ['1039574722163249233', '550239177837379594', '966099744202055811', '499046116386406440'],
    "upscale_steps": 15,
    "upscale_denoise": 0.3,
    "upscale_scale": 2.5,
    "ksampler_scheduler": normal,
}