{
    "maintenance": False,
    "sdxl": False,
    "sdxl_max_steps": 29,
    "max_loras": 5,
    "max_loras_sdxl": 3,
    "sd3_resolution_multiplier": 1,
    "sdxl_resolution_multiplier": 1,
    "sd15_resolution_multiplier": 1,
    "upscale": True,
    "sd3_users": ['1039574722163249233', '550239177837379594', '966099744202055811', '499046116386406440']
}